#+title: Springcloud
#+date:  2021-01-19T11:12:46+08:00
#+weight: 5


** soul springcloud 

*** 实践
**** 在soul中增加springcloud配置
     - 将soul-boostrap中有关springcloud的依赖注释打开,注册中心选用的eureka.
       docker镜像没下载成功,按照教程 [[https://www.baeldung.com/spring-cloud-netflix-eureka][eureka tutor]], 创建springboot项目,引入
       eureka相关依赖,搞定eureka的server服务.
     - soul-admin 中 打开springcloud插件开关
       系统管理 --> 插件管理  (直接保存就ok)
**** 请求调用
     #+begin_src shell
      ### 测试查询数据
      GET http://localhost:9195/springcloud/order/findById?id=999
        {
          "id": "999",
          "name": "hello world spring cloud findById"
        }

      ### 测试保存数据
      POST http://localhost:9195/springcloud/order/save
      Content-Type: application/json

      {
        "id": "999",
        "name": "valjean"
      }

       {
         "id": "999",
         "name": "hello world spring cloud save order"
       }


     #+end_src
** tars cloud
   又发现一个新的rpc框架[[https://tarscloud.org/][tarscloud]], 原来以为是个压缩相关的模块的呢, ~tars~嘛.  引用下官方的一个项目说明
   #+begin_quote
   TARS是Linux基金会的开源项目，它是基于名字服务使用TARS协议的高性能RPC开发框架， \\
   配套一体化的运营管理平台，并通过伸缩调度，实现运维半托管服务。
   TARS是腾讯从2008年到今天一直在使用的后台逻辑层的统一应用框架，覆盖腾讯100多个产品。\\
   目前支持C++,Java,PHP,Nodejs,Go语言。该框架为用户提供了涉及到开发、运维、以及测试的一整套解决方案，\\
   帮助一个产品或者服务快速开发、部署、测试、上线。 它集可扩展协议编解码、高性能RPC通信框架、名字路由与发现、发布监控、日志统计、配置管理等于一体， \\
   通过它可以快速用微服务的方式构建自己的稳定可靠的分布式应用，并实现完整有效的服务治理。 \\
   目前该框架在腾讯内部，各大核心业务都在使用，颇受欢迎，基于该框架部署运行的服务节点规模达到上万个。
   #+end_quote
  [[https://tarscloud.github.io/TarsDocs/][office docs]] 
  通过soul,前几天接触到阿里的sofa,今天又接触到腾讯的tars. 虽说目前用不上,但是真的蛮开眼界的
  只大概看了一些官方文档的资料,目前还没有跑起来. 明天继续.
