#+title: 心得体会
#+date:  2021-01-21T22:45:24+08:00
#+weight: 5


*** 一 做到、学到的
   
    在这6天里,不管记录的多少、了解的深浅. 在这个大的环境中,一直跟着大家在坚持.
    每天多多少少都学到了新的东西. 从第一天的环境搭建,正好将自己刚学习的hugo+github
    搭建个人博客的给充分的实践起来. 目前不仅在记录学习使用soul的点点滴滴,也在小组内部
    逐步推广起来. 完善工作中的一些琐碎内容的收集和展示.

    再有之后,学习soul的使用从 divide--> http --> sofa --> springcloud --> tars. 自己暂时还没有太多的
    源码解读,但是整个过程也是收货颇丰的,拓展了视野的范围. 比如: soul作为业务网关,可以
    在自己的打点项目中,对在流量网关之后做些数据分流、数据复制,相对的比openresty之类的
    流量网关好维护、控制一些.再个就是新了解到的sofa和tars,虽没有太深入的了解,但是通过
    简单的搭建使用,至少知道有些事情确实可以做到的. 这点确实特别兴奋.

    当然,在这段时间里,自己做的确实不够好. 有些时候也有点马虎. 看着其他的小伙伴那么认真
    投入. 真的特别敬佩他们. 想起一句话 *以大多数人的努力程度之低，根本轮不到拼天赋* .
    再努力和坚持,希望能和大家走到最后的.
   
*** 二 待改善的

    - 时间安排
      睡的太晚,确实有点吃不消的. 尽量将学习的时间调的早一些. 还得以工作内容为主,在soul学习
      这块坚持每天有输出就好. 在完成基础任务之上,跟着大家学习.
    - 任务安排
      按照自己的时间和精力,规划好自己的节奏和目标. 没法像其他同学那么拼,但至少每天要有一点进步
      每天要成长一些. 
    - 落下的任务
      在过去几天落下的一些任务
      - soul-tars 的实践,tars的环境已经搭建完毕,尝试将soul-tars的模块跑起来.
      - webflux的学习实践
      - soul http dubbo插件的学习

*** 三 下周目标
    - 完成基本的任务.soul-admin soul-boostrap之间的数据同步
    - 在使用的基础之上,解读部分模块的源码. 
